require "uuidtools"

module Spider; module DataTypes

    # RFC 4122 UUID

    class UUID < String
        include DataType
        autogenerated
        
        def map(mapper_type)
            self.to_s
        end
        
        # format :short returns just the first part
        def format(type = :normal)
            if (type == :short)
                return self.to_s.split('-')[0]
            end
            return super
        end
        
        def self.generate
            UUIDTools::UUID.random_create.to_s
        end
        
        def self.auto_value
            generate
        end

    end
    
    
end; end