module Spider; module Model

    module Synchronized

        def self.extended(model)
            model.extend(ClassMethods)
        end
        
        def self.included(model)
            model.extend(ClassMethods)
        end

        module ClassMethods

            def synchronizing(name=nil) 
                return @synchronizing unless name
                @synchronizing = name

                with_mapper do
                    
                    def before_save(obj)
                        return super unless @model.synchronizing
                        obj = get_synchronized(obj)
                        super(obj)
                    end
                    
                    def get_synchronized(obj)
                        @model.elements_array.select{ |el| 
                            el.model? && el.model.include?(Synchronized) && el.model.synchronizing == @model.synchronizing
                        }.each do |el|
                            cond = Condition.new
                            el.model.primary_keys.each{ |k| cond[el.model.syncronization_key(@model.synchronizing, k)] = obj.get(k) }
                            res = el.model.find(cond)
                            raise SynchronizationException, "The synchronized object was not unique" if res.length > 1
                            if (res.length == 1)
                                el.model.primary_keys.each{ |k| obj.get(el).set(k, res.get(k))}
                            end
                        end
                        return obj
                    end
                    
                end
                
            end

            def synchronization(name)
                @synchronizations ||= []
                @synchronizations << name
                self.primary_keys.each do |k|
                    element(synchronization_key(name, k), k.type) if k.autogenerated?
                end
            end
            
            def synchronization_key(synchronization, key)
                return key.name unless key.autogenerated?
                return :"sync_#{synchronization}_#{key.name}"
            end


        end

        class SynchronizationException < RuntimeError
        end

    end

end; end
