source "http://rubygems.org"

# Place your gems here


# Spider

gem "spiderfw" #, :path => ''


# Database gems

# gem "mysql", :group => :mysql
# gem "ruby-oci8", :group => :oci8

# Optional gems

gem "json", :platforms => [:mri_18, :mri_19]
gem "mongrel", :platforms => [:ruby_18, :mingw_18]
# gem "mongrel", ">= 1.2.0.pre2" # replace previous line with this for Mongrel on 1.9
gem "ripl", :platforms => [:ruby, :mingw]
gem "ripl-irb", :platforms => [:ruby, :mingw]
gem "ripl-multi_line", :platforms => [:ruby, :mingw]
gem "cldr"
gem "ruby-debug", :group => :devel, :platforms => [:mri_18]
gem "ruby-debug19", :group => :devel, :platforms => [:mri_19], :require => 'ruby-debug'
gem "ruby-prof", :group => :devel
gem "rspec", :group => :test
gem "cucumber", '~> 0.10.0', :group => :test
gem "capybara", :group => :test
gem "yui-compressor", :group => :production
gem "fssm", :group => :devel

if RUBY_PLATFORM =~ /darwin/
  gem "rb-fsevent", :group => :devel, :platforms => [:mri]
end
if RUBY_PLATFORM =~ /linux/
  gem "rb-inotify", :group => :devel, :platforms => [:mri]
end

# Include app Gemfiles

Dir.glob("apps/*/Gemfile") do |f|
  self.instance_eval(Bundler.read_file(f), f, 1)
end