begin
    require 'less-js'
rescue LoadError
    raise "Please install less-js gem to compile less files"
end

module Spider
    
    module LessCompiler

        def intialize(base_path)
            @base_path = base_path
        end
        
        def compile(src, dest)
            output = LessJs.compile File.read(src)
            File.open(dest, 'w') do |f|
                f.write "/* This file is autogenerated; do not edit directly (edit #{src} instead) */\n\n"
                f.write output
            end
        end
        
    end
    
end