require 'less-js'

module Spider
    
    module LessCompiler
        
        def self.compile(src, dest)
            output = LessJs.compile File.read(src)
            File.open(dest, 'w') do |f|
                f.write "/* This file is autogenerated; do not edit directly (edit #{src} instead) */\n\n"
                f.write output
            end
        end
        
    end
    
end