require 'sass'
require 'sass/plugin'

Sass::Plugin.options[:cache_location] = File.join(Spider.paths[:tmp], 'sass-cache')

module Spider
    
    module SassCompiler
        
        def self.compile(src, dest)
            engine = Sass::Engine.for_file(src, {})
            output = engine.render
            File.open(dest, 'w') do |f|
                f.write "/* This file is autogenerated; do not edit directly (edit #{src} instead) */\n\n"
                f.write output
            end
        end
        
    end
    
end