require 'ruby-debug'
require 'spiderfw/utils/monkey/kernel'
require 'spiderfw/utils/monkey/class'
require 'spiderfw/utils/inflector'
require 'spiderfw/i18n/tmp_gettext'
require 'spiderfw/config/configuration'
require 'spiderfw/config/configurable'